name: build
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build binaries
    permissions:
      contents: write
    runs-on: windows-2019
    steps:
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        name: Install msys
        with:
          update: true
          install: >-
            patch
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
      - name: Copy and patch
        shell: msys2 {0}
        run: ./copy_and_patch.bat
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Build
        shell: msys2 {0}
        run: ./build.bat
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate lib files
        run: ./dll2lib.bat 64 curl\bin\libcurl.dll
      - name: Build tarball
        shell: msys2 {0}
        run: tar cvzf curl-impersonate-win.tar.gz -C curl/bin .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: curl-impersonate-win.tar.gz
